name: 1.20 Enhancement
description: Suggest a change to existing 1.20 features
labels: [1.20, Enhancement, Unreviewed]
body:
  - type: markdown
    attributes:
      value: |
        If your idea requires discussion or is complicated, [join our discord](https://discord.gg/mgaZt4GND5) instead of posting a new issue.
        Please search the following links to make sure your enhancement is not covered:
  
  - type: markdown
    attributes:
      value: "## Versions"
      
  - type: markdown
    attributes:
      value: |
        List the last version of the mod you played before making this suggestion, to ensure you are not missing new features.
  
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      value: 1.20.1
    validations:
      required: true
  - type: input
    id: fabric-version
    attributes:
      label: Fabric Version
      placeholder: "Ex: 0.90.4-1.20.1"
    validations:
      required: true
  - type: input
    id: hephaestus-version
    attributes:
      label: "Supporoform Version"
      description: "'Latest' is not a valid answer, write an exact version number"
    validations:
      required: true
  
  
  - type: markdown
    attributes:
      value: "## Enhancement Description"

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: "Describe the reason for this suggestion, what is the problem you are trying to solve?"
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: "Describe the solution you would suggest to the above problem"
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Describe any alternatives you have considered to your suggested solution"
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "If there is any additional context needed, such as screenshots or related mods, include here"
    validations:
      required: false
        
        
  - type: markdown
    attributes:
      value: "## Confirm the following"
      
  - type: dropdown
    id: searched
    attributes:
      label: "Searched for existing enhancement?"
      description: "Select all that apply. Please check the [search bar](/SlimeKnights/TinkersConstruct/issues), and [the FAQ](/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ) to see if your enhancement is covered."
      multiple: true
      options:
        - 'Used the search bar'
        - 'Checked the FAQ'
        - 'Checked the in game books'
        - 'I did not search'
    validations:
      required: true
